### ISSUE TITLE
Cliente cancela pedido

### ISSUE THREAD

**Issue by reginadiana** [TreinaDev/checkout_area_do_cliente#12]
Eu, como cliente do sistema, gostaria de cancelar um pedido antes de ser aprovado/recusado pelo sistema de gestão para que o pedido não seja efetivado e eu não seja cobrado por isso.

**Comment by AvilaLima** [comment]
Solicitar o motivo do cancelamento, sob deferimento ou não da solicitação da Gestão Interna.
