### ISSUE TITLE
Vendedor reprova pedido

### ISSUE THREAD

**Issue by joaorsalmeida** [TreinaDev/checkout_area_do_cliente#22]
Eu, vendedor do sistema, gostaria de **reprovar** um pedido, para evitar que clientes contratem os bots sem ter a infraestrutura necessária para utilizar o serviço.

Ao reprovar um pedido, devo ser capaz de informar o motivo para que outros funcionários da empresa tenham acesso a essa informação.

**Comment by librity** [comment]
PR: https://github.com/TreinaDev/checkout_area_do_cliente/pull/57
