### ISSUE TITLE
Cliente vê planos

### ISSUE THREAD

**Issue by namae-no-nai** [TreinaDev/checkout_area_do_cliente#5]
Eu, usário do sistema, vejo todos os planos oferecidos na home

**Comment by joaorsalmeida** [comment]
Parece duplicado com esse: https://github.com/TreinaDev/checkout_area_do_cliente/projects/1#card-40541116

Vou fechar por enquanto, se tivesse outro propósito podemos detalhar melhor e levar de volta pro quadro.
