### ISSUE TITLE
Cliente cadastra uma empresa (Gestão do Cliente)

### ISSUE THREAD

**Issue by reginadiana** [TreinaDev/checkout_area_do_cliente#6]
Eu, como cliente, gostaria de cadastrar a minha empresa, inserindo informações como:

- Nome fantasia 
- Razão social, 
- Email da empresa,
- CNPJ
- Endereço do faturamento

As informações da empresa devem ser enviadas ao **sistema de gerenciamento** junto com um token ao registrar ou editar os dados.

**Comment by TenaniLucas** [comment]
O sistema valida todas as informações, não podendo deixar nada em branco e também validando se o numero inserido no CNPJ é valido.
